version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tem-smartpol_postgres
    environment:
      POSTGRES_USER: temp-smartpol_user
      POSTGRES_PASSWORD: temp-smartpol_password
      POSTGRES_DB: temp-smartpol_db
    ports:
      - "5236:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartpol_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartpol_user -d smartpol_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  smartpol_network:
    driver: bridge
